### PR TITLE
Parasitic capacitance values from capiche

### PR DESCRIPTION
**Pull request by mole99**
The following changes are included (with notes):

- Renamed sg13g2 to the full name of the PDK variant ihp-sg13g2
- Add preliminary parasitic capacitance values from capiche
  - Missing values for deep n-well
  - Use allactivenonfet instead of ndiff/hvndiff
    - But: allactivenonfet includes normal and hv diff, different results from capiche
  - Nominal values use (lvs) variant, is that correct? sky130A used (orig) which does not exist in ihp.

On the todo list:

- tech: Add values for extresist
- magicrc: source other files relative to its path?
  - it does not make sense to specify open_pdks/volare installation directory
  - simply source the files in the same directory
- Update copyright and license information
- Delete ihp-sg13g2.tech.orig?

### CODE REVIEW

**Review by RTimothyEdwards — APPROVED** [review]
Looks good to me.  I previously changed all `ihp-sg13g2` to `sg13g2` but I can't remember exactly why other than simplification.  I feel like there was a good reason that I did so, but I can't remember exactly what.

**Comment by RTimothyEdwards** [comment]
As for the other questions:
(1) You don't calculate capacitance to deep nwell.  Deep nwell is buried, and nwell or pwell on top of it is a conducting layer.
(2) Use `alldifflvnonfet` and `alldiffhvnonfet` if you want to differentiate between low and high voltage devices.
(3) I need to revisit the use of (orig) in sky130A.  However, do not use `(lvs)`.  That is specifically for LVS extraction in the usual style of commercial tools and klayout (extracts low-level device models, not subcircuit models).  Parasitic capacitance is _never_ a feature of LVS netlists.  Use style `ngspice()` for the nominal case (not high/low capacitance).

**Comment by mole99** [comment]
1. Hm, what is this section in sky130A for?

```
#deep n-well
defaultareacap     dnwell dwell 120

#p-well
defaultoverlap     pwell well dnwell dwell 120

#n-well
# NOTE:  This value not found in PEX files
defaultareacap     nwell well dnwell dwell 120
```

2. Okay, will look into this!

3. Makes sense regarding LVS. Do I use `variants ()` instead of `variants (),(lvs)` to use style `ngspice()`?

I think we can merge this PR already and work on the other issues in a next one.

**Comment by RTimothyEdwards** [comment]
The deep nwell entries in the sky130 extraction deck are for providing some capacitance value related to the reverse-biased diode formed between deep nwell and substrate (and for the next line, pwell to deep nwell).  The line after that (nwell to deep nwell) is probably a mistake, since those are electrically connected (it would make no difference to simulation but shouldn't be there).  In principle, the correct action would be to extract a parasitic diode with the correct area, but as magic doesn't do that, an estimate of the capacitance is a halfway reasonable substitute (assumes that the voltage across the diode is fixed, which is not the case for wells not held at the power supply rails).

**Comment by mole99** [comment]
Thanks for the explanation!

I think you can merge this so we are both using the renamed files and I will work on the other two items (assuming point 3 was correct).

**Comment by RTimothyEdwards** [comment]
And for (3), use `variants ()`.  It looks like this was done wrong in sky130, but also probably doesn't matter because the component styles for LVS isn't used in the magic-netgen extraction and LVS flow.

**Comment by RTimothyEdwards** [comment]
@mole99 :  I will go ahead and merge, and fixes can be added in a separate PR as you suggest.

**Comment by RTimothyEdwards** [comment]
@mole99 :  Also, in the next PR you can remove the ".orig" tech files, which were meant to keep some of the sky130 content to remind myself how the DRC and extraction sections should be written, while I removed those sections from my working tech file to test the work in progress.

**Comment by mole99** [comment]
Thanks, will do! But you misunderstood my previous comment, `variants (),(lvs)` is what I had currently used in ihp, which will be changed. sky130A correctly uses `variants (),(orig),(si)`. So all good!

**Comment by RTimothyEdwards** [comment]
@mole99 :  No, I think the `(orig)` should not be in the variants list for the parasitic caps in sky130.  Of course, parasitics can always be ignored when generating the netlist, and normally are when doing extraction for LVS.  So it's not a big issue, but makes more sense if it's just for the nominal case and corner cases.

**Comment by mole99** [comment]
I can open a PR to remove that, as well as the nwell to deep nwell capacitance.

**Pull request merged**
